<?php
namespace AppBundle\Controller;


use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\Arrivee;
use AppBundle\Entity\Expediteurs;
use AppBundle\Form\FormArrivee;


class DefaultController extends Controller
{
    /**
     * @Route("/", name="welcome")
     */
    public function showAction(Request $request)
    {


        return $this->render('auth/login.html.twig');
    }

    /**
     * @Route("/addarrivee", name="addarrivee")
     */
    public function addarriveeAction(Request $request)
    {

        $em = $this->getDoctrine()->getManager();
        $arrivee = new Arrivee();
        $formArrivee = $this->createForm(FormArrivee::class, $arrivee);
        $formArrivee->handleRequest($request);
        

        if ( $formArrivee->isSubmitted() && $formArrivee->isValid()) {
          
            $Expediteur = new Expediteurs();


            

            $Expediteur->setExpediteur($request->get('Expediteur'));
            $Expediteur->setTel($request->get('Tel'));
            $Expediteur->setFax($request->get('Fax'));
            $em->persist($Expediteur);
            $em->flush();


            $dateCreation = new \DateTime();
           //var_dump($request->get('Nom'),$request->get('Prenom'),$request->get('Civilite'));die;
            $arrivee->setDateCreation($dateCreation);
            $arrivee->setExpediteur($Expediteur);

            
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            $file = $arrivee->getFichier();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            try {
                $file->move(
                    $this->getParameter('brochures_directory'),
                    $fileName
                );
            } catch (FileException $e) {

            }
            $arrivee->setFichier($fileName);
            $em->persist($arrivee);
            $em->flush();


            return $this->redirectToRoute('ListeArrivee');
        }

        // $lastArrivee = $em->getRepository('AppBundle:Arrivee')->findOneBy(array(), array('id' => 'DESC'));
        // var_dump($lastArrivee->getId());die;
        return $this->render('Arrivees/ajouterArrivee.html.twig', [
            'formArrivee' => $formArrivee->createView(),
        ]);
    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


    /**
     * @Route("/ListeArrivee", name="ListeArrivee")
     */
    public function ListeArriveeAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $arrivees = $em->getRepository('AppBundle:Arrivee')->findAll();

        return $this->render('Arrivees/ListeArrivees.html.twig', array(
            'arrivees'           => $arrivees
        ));
    }
}