<?php

namespace AppBundle\Repository;

/**
 * CourriersArriveeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourriersArriveeRepository extends \Doctrine\ORM\EntityRepository
{
}
