<?php

namespace AppBundle\Repository;

/**
 * DepartementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementsRepository extends \Doctrine\ORM\EntityRepository
{
}
