<?php

namespace AppBundle\Repository;

/**
 * ExpediteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpediteursRepository extends \Doctrine\ORM\EntityRepository
{
}
