<?php

namespace AppBundle\Repository;

/**
 * PersonnelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnelsRepository extends \Doctrine\ORM\EntityRepository
{
}
